---
title: "Base R histogram"
author: "李雄辉"
date: "2017/5/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 作用

在统计学中，直方图（Histogram）是一种对数据分布情况的图形表示，是一种二维统计图表，它的两个坐标分别是统计样本和该样本对应的某个属性的度量。


https://en.wikipedia.org/wiki/Histogram

## 用法

```{r}
ds <- c(4.37, 3.87, 4.00, 4.03, 3.50, 4.08, 2.25, 4.70, 1.73, 4.93, 1.73, 4.62,
3.43, 4.25, 1.68, 3.92, 3.68, 3.10, 4.03, 1.77, 4.08, 1.75, 3.20, 1.85,
4.62, 1.97, 4.50, 3.92, 4.35, 2.33, 3.83, 1.88, 4.60, 1.80, 4.73, 1.77,
4.57, 1.85, 3.52, 4.00, 3.70, 3.72, 4.25, 3.58, 3.80, 3.77, 3.75, 2.50,
4.50, 4.10, 3.70, 3.80, 3.43, 4.00, 2.27, 4.40, 4.05, 4.25, 3.33, 2.00,
4.33, 2.93, 4.58, 1.90, 3.58, 3.73, 3.73, 1.82, 4.63, 3.50, 4.00, 3.67,
1.67, 4.60, 1.67, 4.00, 1.80, 4.42, 1.90, 4.63, 2.93, 3.50, 1.97, 4.28,
1.83, 4.13, 1.83, 4.65, 4.20, 3.93, 4.33, 1.83, 4.53, 2.03, 4.18, 4.43,
4.07, 4.13, 3.95, 4.10, 2.72, 4.58, 1.90, 4.50, 1.95, 4.83, 4.12)

ds

hist(ds)  
```

## 参数

```{r}

hist(mtcars$wt)

hist(mtcars$wt, xlab = "Weight")

hist(mtcars$wt, xlab = "Weight", main = "Histogram of Weight")

hist(mtcars$wt, xlab = "Weight", col = "red")

hist(mtcars$wt, xlab = "Weight", border = "blue")

hist(mtcars$wt, xlab = "Weight", col = "red", border = "blue")
```

### 组间距

```{r}
summary(mtcars$wt)

p <- hist(mtcars$wt, plot = FALSE)
print(p)
plot(p)

hist(mtcars$wt)
hist(mtcars$wt, breaks = seq(1,6,1))
hist(mtcars$wt, breaks = seq(1,6,0.5))


hist(ds)
hist(ds, 1)
hist(ds, 2)
hist(ds, 3)
hist(ds, 4)
hist(ds, 5)
hist(ds, 10)
hist(ds, 15)
hist(ds, 30)
hist(ds, 100)
```

## 密度估计


```{r}
hist(ds, prob = T) # 密度图
lines(density(ds)) # 概率密度曲线
rug(jitter(ds))    # 轴须图
```

















end.
